#!/bin/bash
num_args="$#"

modified_string="scalac"

for ((i=1; i<=num_args; i++)); do
  arg="${!i}"

  modified_string="${modified_string} P${arg}.scala"
  if [ "$i" -eq "$num_args" ]; then
    modified_string="${modified_string} && scala P${arg}"
  fi
done

eval "$modified_string"
rm -f *.class *.tasty
